services:
  modsec3-nginx:
    container_name: modsec3-nginx
    image: owasp/modsecurity-crs:4.0.0-nginx-202402261002
    environment:
      #Common ENV Variables
      BACKEND: "http://192.168.1.233:3000"
      SERVER_NAME: modsec3-nginx
      #NGINX ENV Variables
      PORT: "80"
      ERRORLOG: "/var/log/modsec_nginx_error.log"
      ACCESSLOG: "/var/log/modsec_nginx_access.log"
      #Modsec ENV Variables
      MODSEC_AUDIT_LOG: "/var/log/modsec_nginx_audit.log"
      MODSEC_AUDIT_LOG_FORMAT: Native
      MODSEC_AUDIT_LOG_TYPE: Serial
      MODSEC_RULE_ENGINE: On
      MODSEC_TMP_DIR: "/tmp"
      MODSEC_RESP_BODY_ACCESS: "On"
      MODSEC_RESP_BODY_MIMETYPE: "text/plain text/html text/xml application/json"
      #CRS Spesific Variables
      BLOCKING_PARANOIA: 2
      COMBINED_FILE_SIZES: "65535"
#    volumes:
#      - "/var/log/:/var/log/"
    ports:
      - "80:80"

  juiceshop_prod:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
